<a href="https://colab.research.google.com/github/suyogy1-bot/Numpy_Pandas/blob/main/Class_notes/Pandas_Assignment_TechMart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment - TechMart Sales Dataset

Load `TechMart_Sales_300Rows.csv` and solve the following questions.

## Q1. Load the CSV file.

In [22]:
import pandas as pd
import numpy as np

df = pd.read_csv('TechMart_Sales_300Rows.csv')

## Q2. Display first 10 rows.

In [23]:
df.head(10)

,Order_ID,Customer_Name,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
0,ORD1001,Anjali Gupta,Laptop,Electronics,HP,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI
1,ORD1002,Deepak Jain,Printer,Office,Canon,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI
2,ORD1003,Harsh Agrawal,Mouse,Accessories,Logitech,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card
3,ORD1004,Pooja Yadav,Monitor,Electronics,Dell,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking
5,ORD1006,Vivek Joshi,Smart Watch,Electronics,Apple,76174,2,Nagpur,MH,12-01-2025,Cancelled,1.0,Very Nice (Recommended),Credit Card
6,ORD1007,Priya Singh,Mouse,Accessories,Logitech,50323,3,Indore,MP,12-06-2025,Pending,4.0,Average Quality (Late Delivery),Credit Card
7,ORD1008,Arjun Mehta,Mouse,Accessories,Logitech,9858,5,Pune,MH,17-05-2025,Cancelled,2.0,Very Nice (Recommended),Cash
8,ORD1009,Simran Kaur,Printer,Office,Canon,73500,2,Pune,MH,15-01-2025,Delivered,3.0,Excellent Product (Fast Delivery),Credit Card
9,ORD1010,Neha Soni,Monitor,Electronics,Dell,28153,5,Indore,MP,24-02-2025,Cancelled,3.0,Nice Product (Value for Money),Debit Card

## Q3. Display last 5 rows.

In [24]:
df.tail(5)

,Order_ID,Customer_Name,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
298,ORD1299,Harsh Agrawal,Keyboard,Accessories,Logitech,43227,2,Nagpur,MH,30-01-2025,Pending,4.0,Nice Product (Value for Money),Net Banking
299,ORD1300,Pooja Yadav,Smart Watch,Electronics,Apple,51951,5,Jaipur,RJ,31-03-2025,Pending,1.0,Nice Product (Value for Money),Net Banking
300,ORD1011,Simran Kaur,Keyboard,Accessories,Logitech,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card
301,ORD1012,Deepak Jain,Printer,Office,Canon,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI
302,ORD1013,Rohit Patel,Keyboard,Accessories,Logitech,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking

## Q4. Check shape, columns and data types.

In [25]:
df.shape

(303, 14)

In [26]:
a = df.columns
for i in a:
  print(i)

Order_ID
Customer_Name
Product
Category
Brand
Price
Quantity
City
State
Order_Date
Delivery_Status
Rating
Review
Payment_Mode

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         303 non-null    object
 1   Customer_Name    303 non-null    object
 2   Product          303 non-null    object
 3   Category         303 non-null    object
 4   Price            303 non-null    int64
 5   Quantity         303 non-null    int64
 6   City             303 non-null    object
 7   State            303 non-null    object
 8   Order_Date       303 non-null    object
 9   Delivery_Status  303 non-null    object
 10  Rating           303 non-null    float64
 11  Review           303 non-null    object
 12  Payment_Mode     303 non-null    object
 13  Total_Amount     303 non-null    int64
dtypes: float64(1), int64(3), object(10)
memory usage: 33.3+ KB

## Q5. Find null values.

In [27]:
df.isnull().sum() # only rating column is having null values

Order_ID           0
Customer_Name      0
Product            0
Category           0
Brand              0
Price              0
Quantity           0
City               0
State              0
Order_Date         0
Delivery_Status    0
Rating             5
Review             0
Payment_Mode       0
dtype: int64

## Q6. Fill missing Rating with 0.

In [28]:
(df['Rating'] == 0).sum()

np.int64(0)

In [29]:
df['Rating'].isna().sum()

np.int64(5)

In [30]:
df['Rating'] = df['Rating'].fillna(0)

In [31]:
(df['Rating'] == 0).sum()

np.int64(5)

In [32]:
df['Rating'].isna().sum()

np.int64(0)

## Q7. Rename `Customer_Name` to `Customer`.

In [64]:
df['Customer_Name'] = df['Customer_Name'].rename('Customer')
df.head()

,Order_ID,Customer_Name,Product,Category,Brand,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
0,ORD1001,Anjali Gupta,Laptop,Electronics,HP,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI
1,ORD1002,Deepak Jain,Printer,Office,Canon,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI
2,ORD1003,Harsh Agrawal,Mouse,Accessories,Logitech,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card
3,ORD1004,Pooja Yadav,Monitor,Electronics,Dell,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,Apple,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking

## Q8. Delete `Brand` column.

In [69]:
df.drop('Brand', axis=1, inplace=True)
# here we are removing brand name column
# That's why axis = 1

df.head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode
0,ORD1001,Anjali Gupta,Laptop,Electronics,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI
1,ORD1002,Deepak Jain,Printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI
2,ORD1003,Harsh Agrawal,Mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card
3,ORD1004,Pooja Yadav,Monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking

## Q9. Create `Total_Amount = Price * Quantity`.

In [70]:
df['Total_Amount'] = df['Price'] * df['Quantity']
df.head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
0,ORD1001,Anjali Gupta,Laptop,Electronics,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI,65196
1,ORD1002,Deepak Jain,Printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI,4405
2,ORD1003,Harsh Agrawal,Mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card,117572
3,ORD1004,Pooja Yadav,Monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card,86163
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780

## Q10. Display only Customer, Product and Total_Amount.

In [71]:
df[['Customer_Name', 'Product', 'Total_Amount']]

        Customer_Name      Product  Total_Amount
0      Anjali Gupta         Laptop         65196
1         Deepak Jain      Printer          4405
2       Harsh Agrawal        Mouse        117572
3         Pooja Yadav      Monitor         86163
4         Arjun Mehta  Smart Watch         24780
..                ...          ...           ...
298     Harsh Agrawal     Keyboard         86454
299     Pooja Yadav    Smart Watch        259755
300       Simran Kaur     Keyboard         37602
301       Deepak Jain      Printer         58492
302       Rohit Patel     Keyboard         78672

[303 rows x 3 columns]

## Q11. Show Delivered orders.

In [72]:
df['Delivery_Status'].unique()

array(['Cancelled', 'Delivered', 'Pending'], dtype=object)

In [84]:
df[df['Delivery_Status'] == 'Delivered'].head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
2,ORD1003,Harsh Agrawal,Mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card,117572
8,ORD1009,Simran Kaur,Printer,Office,73500,2,Pune,MH,15-01-2025,Delivered,3.0,Excellent Product (Fast Delivery),Credit Card,147000
11,ORD1012,Deepak Jain,Printer,Office,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI,58492
16,ORD1017,Sakshi Sharma,Tablet,Electronics,3052,1,Hyderabad,TS,20-03-2025,Delivered,3.0,Excellent Product (Fast Delivery),Cash,3052
17,ORD1018,Deepak Jain,Mobile,Electronics,64199,1,Indore,MP,02-02-2025,Delivered,5.0,Nice Product (Value for Money),Net Banking,64199

In [74]:
df[df['Delivery_Status'] == 'Delivered'].shape

(88, 14)

In [77]:
(df['Delivery_Status'] == 'Delivered').sum()

np.int64(88)

## Q12. Show products with Price > 50000.

In [82]:
df[df['Price'] > 50000].head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
5,ORD1006,Vivek Joshi,Smart Watch,Electronics,76174,2,Nagpur,MH,12-01-2025,Cancelled,1.0,Very Nice (Recommended),Credit Card,152348
6,ORD1007,Priya Singh,Mouse,Accessories,50323,3,Indore,MP,12-06-2025,Pending,4.0,Average Quality (Late Delivery),Credit Card,150969
8,ORD1009,Simran Kaur,Printer,Office,73500,2,Pune,MH,15-01-2025,Delivered,3.0,Excellent Product (Fast Delivery),Credit Card,147000
12,ORD1013,Rohit Patel,Keyboard,Accessories,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product (Value for Money),Net Banking,78672
17,ORD1018,Deepak Jain,Mobile,Electronics,64199,1,Indore,MP,02-02-2025,Delivered,5.0,Nice Product (Value for Money),Net Banking,64199

In [79]:
df[df['Price'] > 50000].shape

(120, 14)

## Q13. Show customers from Bhopal.

In [83]:
df[df['City'] == 'Bhopal'].head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
1,ORD1002,Deepak Jain,Printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI,4405
13,ORD1014,Nikita Rao,Headphone,Accessories,15514,5,Bhopal,MP,14-06-2025,Pending,3.0,Good Product (Satisfied),Credit Card,77570
43,ORD1044,Karan Shah,Mouse,Accessories,25813,4,Bhopal,MP,13-03-2025,Delivered,3.0,Worth Buying (Happy Customer),Credit Card,103252
61,ORD1062,Mohit Gupta,Speaker,Accessories,51468,3,Bhopal,MP,12-02-2025,Pending,4.0,Average Quality (Late Delivery),Net Banking,154404
63,ORD1064,Simran Kaur,Keyboard,Accessories,34599,4,Bhopal,MP,24-02-2025,Pending,3.0,Bad Packaging (Delayed),Credit Card,138396

In [81]:
df[df['City'] == 'Bhopal'].shape

(32, 14)

## Q14. Show Rating >= 4.

In [85]:
df[df['Rating'] >= 4].head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
2,ORD1003,Harsh Agrawal,Mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card,117572
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780
6,ORD1007,Priya Singh,Mouse,Accessories,50323,3,Indore,MP,12-06-2025,Pending,4.0,Average Quality (Late Delivery),Credit Card,150969
10,ORD1011,Simran Kaur,Keyboard,Accessories,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing (5 Stars),Debit Card,37602
11,ORD1012,Deepak Jain,Printer,Office,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product (Fast Delivery),UPI,58492

In [86]:
df[df['Rating'] >= 4].shape

(132, 14)

## Q15. Show Electronics category.

In [88]:
df['Category'].unique()

array(['Electronics', 'Office', 'Accessories'], dtype=object)

In [87]:
df[df['Category'] == 'Electronics'].head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
0,ORD1001,Anjali Gupta,Laptop,Electronics,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI,65196
3,ORD1004,Pooja Yadav,Monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card,86163
4,ORD1005,Arjun Mehta,Smart Watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780
5,ORD1006,Vivek Joshi,Smart Watch,Electronics,76174,2,Nagpur,MH,12-01-2025,Cancelled,1.0,Very Nice (Recommended),Credit Card,152348
9,ORD1010,Neha Soni,Monitor,Electronics,28153,5,Indore,MP,24-02-2025,Cancelled,3.0,Nice Product (Value for Money),Debit Card,140765

## Q16. Sort by Price (Ascending).

In [89]:
df.sort_values(by='Price').head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
101,ORD1102,Pooja Yadav,Headphone,Accessories,836,3,Pune,MH,31-05-2025,Cancelled,3.0,Nice Product (Value for Money),Cash,2508
14,ORD1015,Mohit Gupta,Keyboard,Accessories,925,3,Hyderabad,TS,15-02-2025,Cancelled,5.0,Good Product (Satisfied),Credit Card,2775
20,ORD1021,Karan Shah,Smart Watch,Electronics,1442,1,Mumbai,MH,28-02-2025,Delivered,1.0,Excellent Product (Fast Delivery),Credit Card,1442
146,ORD1147,Neha Soni,Smart Watch,Electronics,1507,2,Bhopal,MP,24-02-2025,Delivered,3.0,Worth Buying (Happy Customer),Credit Card,3014
279,ORD1280,Sakshi Sharma,Tablet,Electronics,2117,3,Jaipur,RJ,10-04-2025,Delivered,4.0,Poor Quality (Returned),Cash,6351

## Q17. Sort by Total_Amount (Descending).

In [91]:
df.sort_values(by='Total_Amount', ascending=False).head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
213,ORD1214,Riya Tiwari,Speaker,Accessories,79963,5,Delhi,Delhi,25-03-2025,Cancelled,2.0,Bad Packaging (Delayed),Cash,399815
282,ORD1283,Nikita Rao,Mouse,Accessories,78331,5,Hyderabad,TS,28-04-2025,Delivered,2.0,Average Quality (Late Delivery),Credit Card,391655
62,ORD1063,Harsh Agrawal,Laptop,Electronics,78080,5,Jaipur,RJ,22-01-2025,Cancelled,1.0,Excellent (Must Buy),Cash,390400
216,ORD1217,Sakshi Sharma,Speaker,Accessories,76321,5,Pune,MH,14-01-2025,Cancelled,2.0,Nice Product (Value for Money),Cash,381605
249,ORD1250,Karan Shah,Smart Watch,Electronics,76190,5,Nagpur,MH,02-03-2025,Pending,3.0,Average Quality (Late Delivery),Net Banking,380950

## Q18. Sort by City then Price.

In [94]:
df.sort_values(by=['City', 'Price']).head()

# This will first sort by cities then based on those cities
# it will sort by price.
# For Example: It will sort cities by ascending order like "Bhopal"
# Then we have multiple values of bhopal, so ...
# It will arrange prices in asceding order within Bhopal.

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
146,ORD1147,Neha Soni,Smart Watch,Electronics,1507,2,Bhopal,MP,24-02-2025,Delivered,3.0,Worth Buying (Happy Customer),Credit Card,3014
1,ORD1002,Deepak Jain,Printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI,4405
242,ORD1243,Arjun Mehta,Mobile,Electronics,9546,4,Bhopal,MP,15-03-2025,Pending,1.0,Average Quality (Late Delivery),Cash,38184
255,ORD1256,Nikita Rao,Printer,Office,10039,2,Bhopal,MP,21-06-2025,Cancelled,5.0,Very Nice (Recommended),Debit Card,20078
273,ORD1274,Riya Tiwari,Tablet,Electronics,13303,4,Bhopal,MP,20-01-2025,Pending,2.0,Amazing (5 Stars),Net Banking,53212

## Q19. Convert Customer to uppercase.

In [95]:
df['Customer_Name'] = df['Customer_Name'].str.upper()
df.head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
0,ORD1001,ANJALI GUPTA,Laptop,Electronics,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI,65196
1,ORD1002,DEEPAK JAIN,Printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI,4405
2,ORD1003,HARSH AGRAWAL,Mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card,117572
3,ORD1004,POOJA YADAV,Monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card,86163
4,ORD1005,ARJUN MEHTA,Smart Watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780

## Q20. Convert Product to lowercase.

In [96]:
df['Product'] = df['Product'].str.lower()
df.head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
0,ORD1001,ANJALI GUPTA,laptop,Electronics,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality (Returned),UPI,65196
1,ORD1002,DEEPAK JAIN,printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing (5 Stars),UPI,4405
2,ORD1003,HARSH AGRAWAL,mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality (Late Delivery),Debit Card,117572
3,ORD1004,POOJA YADAV,monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product (Satisfied),Credit Card,86163
4,ORD1005,ARJUN MEHTA,smart watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product (Satisfied),Net Banking,24780

## Q21. Remove everything after '(' from Review.

In [109]:
b = "Average Quality (Late Delivery)"
b_list = b.split('(')
b_list

['Average Quality ', 'Late Delivery)']

In [106]:
b_list[0]

'Average Quality '

In [107]:
c = b_list[0].strip()
c

'Average Quality'

In [97]:
a = df['Review'].str.split('(')
a.str[0]

0           Poor Quality
1                Amazing
2        Average Quality
3           Good Product
4           Good Product
              ...
298         Nice Product
299         Nice Product
300              Amazing
301    Excellent Product
302         Nice Product
Name: Review, Length: 303, dtype: object

In [110]:
df['Review'] = df['Review'].str.split('(').str[0]
df.head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
0,ORD1001,ANJALI GUPTA,laptop,Electronics,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality,UPI,65196
1,ORD1002,DEEPAK JAIN,printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing,UPI,4405
2,ORD1003,HARSH AGRAWAL,mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality,Debit Card,117572
3,ORD1004,POOJA YADAV,monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product,Credit Card,86163
4,ORD1005,ARJUN MEHTA,smart watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product,Net Banking,24780

## Q22. Find customers whose names start with 'A'.

In [111]:
df[df['Customer_Name'].str.startswith('A')].head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
4,ORD1005,ARJUN MEHTA,smart watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product,Net Banking,24780
7,ORD1008,ARJUN MEHTA,mouse,Accessories,9858,5,Pune,MH,17-05-2025,Cancelled,2.0,Very Nice,Cash,49290
22,ORD1023,AKASH DUBEY,mouse,Accessories,53854,2,Hyderabad,TS,25-01-2025,Cancelled,1.0,Excellent,Credit Card,107708
29,ORD1030,AMAN VERMA,smart watch,Electronics,66409,5,Hyderabad,TS,15-01-2025,Cancelled,2.0,Good Product,Cash,332045
31,ORD1032,AMAN VERMA,smart watch,Electronics,55448,5,Indore,MP,14-05-2025,Pending,5.0,Worth Buying,Cash,277240

## Q23. Find reviews containing 'Good'.

In [112]:
df[df['Review'].str.contains('Good')].head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
3,ORD1004,POOJA YADAV,monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product,Credit Card,86163
4,ORD1005,ARJUN MEHTA,smart watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product,Net Banking,24780
13,ORD1014,NIKITA RAO,headphone,Accessories,15514,5,Bhopal,MP,14-06-2025,Pending,3.0,Good Product,Credit Card,77570
14,ORD1015,MOHIT GUPTA,keyboard,Accessories,925,3,Hyderabad,TS,15-02-2025,Cancelled,5.0,Good Product,Credit Card,2775
29,ORD1030,AMAN VERMA,smart watch,Electronics,66409,5,Hyderabad,TS,15-01-2025,Cancelled,2.0,Good Product,Cash,332045

## Q24. Remove extra spaces from Customer.

In [113]:
df['Customer_Name'] = df['Customer_Name'].str.strip()
df.head()

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
0,ORD1001,ANJALI GUPTA,laptop,Electronics,32598,2,Pune,MH,27-01-2025,Cancelled,2.0,Poor Quality,UPI,65196
1,ORD1002,DEEPAK JAIN,printer,Office,4405,1,Bhopal,MP,01-03-2025,Cancelled,2.0,Amazing,UPI,4405
2,ORD1003,HARSH AGRAWAL,mouse,Accessories,29393,4,Jaipur,RJ,13-03-2025,Delivered,5.0,Average Quality,Debit Card,117572
3,ORD1004,POOJA YADAV,monitor,Electronics,28721,3,Delhi,Delhi,24-01-2025,Pending,1.0,Good Product,Credit Card,86163
4,ORD1005,ARJUN MEHTA,smart watch,Electronics,6195,4,Pune,MH,01-02-2025,Pending,5.0,Good Product,Net Banking,24780

## Q25. Category-wise total sales.

In [114]:
df.groupby('Category')['Total_Amount'].sum()

Category
Accessories    15627647
Electronics    17974270
Office          3383852
Name: Total_Amount, dtype: int64

## Q26. Brand-wise average price.

In [116]:
# This will give error because we have already dropped the brand column

df.groupby('Brand')['Price'].mean()

KeyError: 'Brand'

## Q27. Category-wise maximum price.

In [117]:
df.groupby('Category')['Price'].max()

Category
Accessories    79963
Electronics    79982
Office         78866
Name: Price, dtype: int64

## Q28. City-wise total quantity.

In [118]:
df.groupby('City')['Quantity'].sum()

City
Bhopal       112
Delhi        103
Hyderabad    122
Indore       106
Jaipur       136
Mumbai        84
Nagpur       111
Pune         121
Name: Quantity, dtype: int64

## Q29. Payment mode-wise average rating.

In [119]:
df.groupby('Payment_Mode')['Rating'].mean()

Payment_Mode
Cash           3.133333
Credit Card    3.046154
Debit Card     3.526316
Net Banking    2.745455
UPI            2.893939
Name: Rating, dtype: float64

## Q30. Count Delivery_Status.

In [120]:
df['Delivery_Status'].value_counts()

Delivery_Status
Cancelled    108
Pending      107
Delivered     88
Name: count, dtype: int64

## Q31. Count Category.

In [121]:
df['Category'].value_counts()

Category
Electronics    145
Accessories    123
Office          35
Name: count, dtype: int64

## Q32. Count Payment_Mode.

In [122]:
df['Payment_Mode'].value_counts()

Payment_Mode
UPI            66
Credit Card    65
Cash           60
Debit Card     57
Net Banking    55
Name: count, dtype: int64

## Q33. Top 5 highest sales.

In [129]:
df.sort_values(by='Total_Amount', ascending=False).head(5)

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
213,ORD1214,RIYA TIWARI,speaker,Accessories,79963,5,Delhi,Delhi,25-03-2025,Cancelled,2.0,Bad Packaging,Cash,399815
282,ORD1283,NIKITA RAO,mouse,Accessories,78331,5,Hyderabad,TS,28-04-2025,Delivered,2.0,Average Quality,Credit Card,391655
62,ORD1063,HARSH AGRAWAL,laptop,Electronics,78080,5,Jaipur,RJ,22-01-2025,Cancelled,1.0,Excellent,Cash,390400
216,ORD1217,SAKSHI SHARMA,speaker,Accessories,76321,5,Pune,MH,14-01-2025,Cancelled,2.0,Nice Product,Cash,381605
249,ORD1250,KARAN SHAH,smart watch,Electronics,76190,5,Nagpur,MH,02-03-2025,Pending,3.0,Average Quality,Net Banking,380950

## Q34. Bottom 5 sales.

In [130]:
df.sort_values(by='Total_Amount', ascending=False).tail(5)

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
16,ORD1017,SAKSHI SHARMA,tablet,Electronics,3052,1,Hyderabad,TS,20-03-2025,Delivered,3.0,Excellent Product,Cash,3052
146,ORD1147,NEHA SONI,smart watch,Electronics,1507,2,Bhopal,MP,24-02-2025,Delivered,3.0,Worth Buying,Credit Card,3014
14,ORD1015,MOHIT GUPTA,keyboard,Accessories,925,3,Hyderabad,TS,15-02-2025,Cancelled,5.0,Good Product,Credit Card,2775
101,ORD1102,POOJA YADAV,headphone,Accessories,836,3,Pune,MH,31-05-2025,Cancelled,3.0,Nice Product,Cash,2508
20,ORD1021,KARAN SHAH,smart watch,Electronics,1442,1,Mumbai,MH,28-02-2025,Delivered,1.0,Excellent Product,Credit Card,1442

## Q35. Find duplicate rows.

In [127]:
df.duplicated().sum()

np.int64(3)

In [128]:
df[df.duplicated()]

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
300,ORD1011,SIMRAN KAUR,keyboard,Accessories,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing,Debit Card,37602
301,ORD1012,DEEPAK JAIN,printer,Office,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product,UPI,58492
302,ORD1013,ROHIT PATEL,keyboard,Accessories,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product,Net Banking,78672

In [131]:
# 1. See which positions are duplicates
df.duplicated()

# 2. See only the duplicates
df[df.duplicated()]

# 3. See original + duplicate together
dupe_mask = df.duplicated(keep=False)
df[dupe_mask].sort_values(by=df.columns.tolist())

,Order_ID,Customer_Name,Product,Category,Price,Quantity,City,State,Order_Date,Delivery_Status,Rating,Review,Payment_Mode,Total_Amount
10,ORD1011,SIMRAN KAUR,keyboard,Accessories,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing,Debit Card,37602
300,ORD1011,SIMRAN KAUR,keyboard,Accessories,18801,2,Pune,MH,18-05-2025,Pending,5.0,Amazing,Debit Card,37602
11,ORD1012,DEEPAK JAIN,printer,Office,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product,UPI,58492
301,ORD1012,DEEPAK JAIN,printer,Office,29246,2,Nagpur,MH,07-05-2025,Delivered,5.0,Excellent Product,UPI,58492
12,ORD1013,ROHIT PATEL,keyboard,Accessories,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product,Net Banking,78672
302,ORD1013,ROHIT PATEL,keyboard,Accessories,78672,1,Jaipur,RJ,08-04-2025,Cancelled,4.0,Nice Product,Net Banking,78672

In [132]:
df.shape

(303, 14)

## Q36. Remove duplicate rows.

In [133]:
df.drop_duplicates(inplace=True)
df.shape

(300, 14)

## Q37. Save cleaned data as `Cleaned_TechMart.csv`.

In [134]:
df.to_csv('Cleaned_TechMart.csv', index=False)

In [135]:
# I can download the above cleaned csv file from the left “Files” panel in Colab.