# 🐼 Pandas Backup Class — E-Commerce Sales & Customer Analytics

Welcome! This notebook is built for **practice, not memorization**.

**Dataset:** `ecommerce_sales_data.csv` — a realistic (but intentionally messy)
e-commerce dataset with customers, orders, and business metrics.

> 💡 Tip: This dataset was created ON PURPOSE with missing values, duplicates,
> wrong data types, inconsistent text, and outliers — because real company
> data always looks like this. Cleaning it is part of the lesson!

## 1. Reading the Dataset — `read_csv`

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("ecommerce_sales_data.csv")


## 2. First Look at the Data — `head`, `tail`, `sample`

In [5]:
df.head()

,Row_ID,Customer_ID,Customer_Name,Gender,Age,City,State,Country,Membership_Type,Order_ID,...,Time_On_Website,Rating,Returned_Product,Customer_Satisfaction,Salesperson,Region,Warehouse,Profit,Cost,Revenue
0,1,CUST00265,Sneha Sharma,Male,35.0,Chennai,Tamil Nadu,India,Gold,ORD103884,...,5.8,4.0,No,Very Satisfied,Agent_15,South,WH-East,543.26,7950.40,10473.10
1,2,CUST01312,Rahul Joshi,Female,23.0,Jaipur,Rajasthan,India,Gold,ORD103992,...,6.7,2.0,No,Very Satisfied,Agent_17,South,WH-Central,316.68,2412.48,3388.61
2,3,CUST00608,Priya Mehta,Male,18.0,Bhopal,Madhya Pradesh,India,Regular,ORD103326,...,15.6,5.0,No,Satisfied,Agent_04,South,WH-East,1536.93,3649.22,6373.82
3,4,CUST00374,Aditya Gupta,F,37.0,Bhopal,Madhya Pradesh,India,Silver,ORD100652,...,17.7,3.0,No,NaN,Agent_19,East,WH-East,362.02,1609.59,2432.95
4,5,CUST00688,Reyansh Singh,Female,27.0,Hyderabad,Telangana,India,Gold,ORD101040,...,5.1,4.0,Yes,Satisfied,Agent_12,East,WH-West,553.81,4702.15,6598.52

In [6]:
df.tail()

,Row_ID,Customer_ID,Customer_Name,Gender,Age,City,State,Country,Membership_Type,Order_ID,...,Time_On_Website,Rating,Returned_Product,Customer_Satisfaction,Salesperson,Region,Warehouse,Profit,Cost,Revenue
4300,4301,CUST00673,Diya Singh,Female,29.0,bhopal,Madhya Pradesh,India,Silver,ORD100919,...,9.5,4.0,No,NaN,Agent_18,North,WH-South,583.64,3831.97,5566.17
4301,4302,CUST01038,Rahul Sharma,Male,49.0,Jaipur,Rajasthan,India,Platinum,ORD102550,...,24.0,4.0,Yes,Unsatisfied,Agent_13,East,WH-Central,942.26,3269.80,5203.57
4302,4303,CUST01417,Rahul Joshi,Female,37.0,Chennai,Tamil Nadu,India,Silver,ORD100537,...,23.6,3.0,No,NaN,Agent_08,North,WH-North,310.56,2318.76,3241.43
4303,4304,CUST00320,Karan Patel,Male,18.0,Bhopal,Madhya Pradesh,India,Platinum,ORD101220,...,11.4,5.0,No,Neutral,Agent_03,East,WH-South,773.99,2396.13,4093.36
4304,4305,CUST00780,Karan Verma,Female,40.0,NaN,Madhya Pradesh,India,Gold,ORD100544,...,4.7,2.0,No,NaN,Agent_03,East,WH-West,487.83,1686.80,2779.98

In [7]:
df.sample()

,Row_ID,Customer_ID,Customer_Name,Gender,Age,City,State,Country,Membership_Type,Order_ID,...,Time_On_Website,Rating,Returned_Product,Customer_Satisfaction,Salesperson,Region,Warehouse,Profit,Cost,Revenue
515,516,CUST01299,Ishaan Reddy,Male,43.0,NaN,Gujarat,India,Silver,ORD101949,...,3.8,4.0,No,Satisfied,Agent_12,West,WH-East,179.68,1282.27,1891.41

## 3. Understanding the Structure — `shape`, `columns`, `dtypes`, `info`, `describe`

In [9]:
df.shape

(4305, 33)

In [10]:
df.columns.tolist()

['Row_ID',
 'Customer_ID',
 'Customer_Name',
 'Gender',
 'Age',
 'City',
 'State',
 'Country',
 'Membership_Type',
 'Order_ID',
 'Order_Date',
 'Delivery_Date',
 'Payment_Method',
 'Order_Status',
 'Product_Category',
 'Product_Name',
 'Quantity',
 'Unit_Price',
 'Discount',
 'Shipping_Cost',
 'Tax',
 'Total_Amount',
 'Website_Visits',
 'Time_On_Website',
 'Rating',
 'Returned_Product',
 'Customer_Satisfaction',
 'Salesperson',
 'Region',
 'Warehouse',
 'Profit',
 'Cost',
 'Revenue']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4305 entries, 0 to 4304
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Row_ID                 4305 non-null   int64
 1   Customer_ID            4305 non-null   object
 2   Customer_Name          4305 non-null   object
 3   Gender                 4305 non-null   object
 4   Age                    3875 non-null   float64
 5   City                   4090 non-null   object
 6   State                  4305 non-null   object
 7   Country                4305 non-null   object
 8   Membership_Type        4305 non-null   object
 9   Order_ID               4305 non-null   object
 10  Order_Date             4305 non-null   object
 11  Delivery_Date          4090 non-null   object
 12  Payment_Method         4305 non-null   object
 13  Order_Status           4305 non-null   object
 14  Product_Category       4305 non-null   object
 15  Product_Name           4305 non-null   object
 16  Quantity               4305 non-null   int64
 17  Unit_Price             4305 non-null   object
 18  Discount               4090 non-null   float64
 19  Shipping_Cost          4305 non-null   float64
 20  Tax                    4305 non-null   float64
 21  Total_Amount           4305 non-null   float64
 22  Website_Visits         4305 non-null   int64
 23  Time_On_Website        4305 non-null   float64
 24  Rating                 3875 non-null   float64
 25  Returned_Product       4305 non-null   object
 26  Customer_Satisfaction  3875 non-null   object
 27  Salesperson            4305 non-null   object
 28  Region                 4305 non-null   object
 29  Warehouse              4305 non-null   object
 30  Profit                 3444 non-null   object
 31  Cost                   4305 non-null   float64
 32  Revenue                4305 non-null   float64
dtypes: float64(9), int64(3), object(21)
memory usage: 1.1+ MB

In [12]:
df.describe()

,Row_ID,Age,Quantity,Discount,Shipping_Cost,Tax,Total_Amount,Website_Visits,Time_On_Website,Rating,Cost,Revenue
count,4305.000000,3875.000000,4305.000000,4090.000000,4305.000000,4305.000000,4305.000000,4305.000000,4305.000000,3875.000000,4305.000000,4305.000000
mean,2153.000000,34.823484,4.164692,12.268120,90.585370,1004.734353,6666.305317,6.221138,11.275796,3.188903,3457.644314,8526.734167
std,1242.890784,11.167811,5.002189,10.190367,243.355182,719.154651,4714.518859,29.459290,35.818504,1.096496,2552.482952,49922.640734
min,1.000000,-5.000000,-4.000000,0.076096,-186.410000,32.680000,317.770000,1.000000,1.000000,-2.000000,110.210000,181.530000
25%,1077.000000,28.000000,3.000000,6.511042,37.760000,488.840000,3279.720000,2.000000,3.200000,2.000000,1658.730000,2725.590000
50%,2153.000000,34.000000,4.000000,10.657993,66.350000,828.590000,5490.060000,3.000000,6.700000,3.000000,2825.550000,4623.320000
75%,3229.000000,41.000000,5.000000,16.177651,106.290000,1312.110000,8707.290000,6.000000,12.400000,4.000000,4519.430000,7329.650000
max,4305.000000,150.000000,120.000000,200.000000,5000.000000,6351.530000,41714.370000,500.000000,600.000000,10.000000,22330.830000,850000.000000

## 4. Selecting Data — Indexing, `loc`, `iloc`

In [14]:
df[['Customer_Name', 'City']]

      Customer_Name       City
0      Sneha Sharma    Chennai
1       Rahul Joshi     Jaipur
2       Priya Mehta     Bhopal
3      Aditya Gupta     Bhopal
4     Reyansh Singh  Hyderabad
...             ...        ...
4300     Diya Singh     bhopal
4301   Rahul Sharma     Jaipur
4302    Rahul Joshi    Chennai
4303    Karan Patel     Bhopal
4304    Karan Verma        NaN

[4305 rows x 2 columns]

In [15]:
df.iloc[:5]

,Row_ID,Customer_ID,Customer_Name,Gender,Age,City,State,Country,Membership_Type,Order_ID,...,Time_On_Website,Rating,Returned_Product,Customer_Satisfaction,Salesperson,Region,Warehouse,Profit,Cost,Revenue
0,1,CUST00265,Sneha Sharma,Male,35.0,Chennai,Tamil Nadu,India,Gold,ORD103884,...,5.8,4.0,No,Very Satisfied,Agent_15,South,WH-East,543.26,7950.40,10473.10
1,2,CUST01312,Rahul Joshi,Female,23.0,Jaipur,Rajasthan,India,Gold,ORD103992,...,6.7,2.0,No,Very Satisfied,Agent_17,South,WH-Central,316.68,2412.48,3388.61
2,3,CUST00608,Priya Mehta,Male,18.0,Bhopal,Madhya Pradesh,India,Regular,ORD103326,...,15.6,5.0,No,Satisfied,Agent_04,South,WH-East,1536.93,3649.22,6373.82
3,4,CUST00374,Aditya Gupta,F,37.0,Bhopal,Madhya Pradesh,India,Silver,ORD100652,...,17.7,3.0,No,NaN,Agent_19,East,WH-East,362.02,1609.59,2432.95
4,5,CUST00688,Reyansh Singh,Female,27.0,Hyderabad,Telangana,India,Gold,ORD101040,...,5.1,4.0,Yes,Satisfied,Agent_12,East,WH-West,553.81,4702.15,6598.52

In [16]:
df.iloc[:5, :3]

   Row_ID Customer_ID  Customer_Name
0       1   CUST00265   Sneha Sharma
1       2   CUST01312    Rahul Joshi
2       3   CUST00608    Priya Mehta
3       4   CUST00374   Aditya Gupta
4       5   CUST00688  Reyansh Singh

In [17]:
df.iloc[-1]

Row_ID                               4305
Customer_ID                     CUST00780
Customer_Name                 Karan Verma
Gender                             Female
Age                                  40.0
City                                  NaN
State                      Madhya Pradesh
Country                             India
Membership_Type                      Gold
Order_ID                        ORD100544
Order_Date                     2023-01-01
Delivery_Date                  01/04/2023
Payment_Method           Cash on Delivery
Order_Status                      Shipped
Product_Category              Electronics
Product_Name                  LED Monitor
Quantity                                4
Unit_Price                          742.6
Discount                         6.410424
Shipping_Cost                      104.95
Tax                                 500.4
Total_Amount                      3385.33
Website_Visits                          2
Time_On_Website                       4.7
Rating                                2.0
Returned_Product                       No
Customer_Satisfaction                 NaN
Salesperson                      Agent_03
Region                               East
Warehouse                         WH-West
Profit                             487.83
Cost                               1686.8
Revenue                           2779.98
Name: 4304, dtype: object

In [18]:
df.loc[0:4, ['Customer_Name', 'City']]

   Customer_Name       City
0   Sneha Sharma    Chennai
1    Rahul Joshi     Jaipur
2    Priya Mehta     Bhopal
3   Aditya Gupta     Bhopal
4  Reyansh Singh  Hyderabad

In [19]:
# All orders from Bhopal
df_bhopal = df[df['City'].str.lower() == 'bhopal']

In [20]:
# Bhopal + only a few columns
df_bhopal_subset = df.loc[df['City'].str.lower() == 'bhopal',
                          ['Customer_Name', 'City', 'Total_Amount', 'Profit']]

In [21]:
# Fix inconsistent city text: 'bhopal' → 'Bhopal'
df.loc[df['City'].str.lower() == 'bhopal', 'City'] = 'Bhopal'

# Cap negative quantities at 0
df.loc[df['Quantity'] < 0, 'Quantity'] = 0

## 5. Filtering Data (Boolean Conditions)

In [23]:
# Customers older than 40
df_age_gt_40 = df[df['Age'] > 40]

# Orders with Revenue greater than 10,000
df_high_revenue = df[df['Revenue'] > 10000]

# Orders paid by Credit Card
df_cc = df[df['Payment_Method'] == 'Credit Card']

In [24]:
# Gold members from Bhopal
df_gold_bhopal = df[
    (df['Membership_Type'] == 'Gold') &
    (df['City'].str.lower() == 'bhopal')
]

# Orders from either Bhopal OR Chennai
df_bhopal_chennai = df[
    (df['City'].str.lower() == 'bhopal') |
    (df['City'].str.lower() == 'chennai')
]

# Non-returned products (not Yes)
df_not_returned = df[df['Returned_Product'] != 'Yes']

# Equivalent using NOT (~)
df_not_returned2 = df[~(df['Returned_Product'] == 'Yes')]

In [25]:
# Membership type in a list of categories
df_premium = df[df['Membership_Type'].isin(['Gold', 'Platinum'])]

# Age between 25 and 35 (inclusive)
df_age_25_35 = df[df['Age'].between(25, 35)]

# Rows where City is missing
df_city_null = df[df['City'].isnull()]

# Rows where Profit is not missing
df_profit_not_null = df[df['Profit'].notnull()]

In [26]:
# Bhopal + Gold or Platinum + high revenue, show only a few columns
mask = (
    (df['City'].str.lower() == 'bhopal') &
    (df['Membership_Type'].isin(['Gold', 'Platinum'])) &
    (df['Revenue'] > 10000)
)

df_filtered = df.loc[mask,
                     ['Customer_Name', 'City', 'Membership_Type',
                      'Revenue', 'Profit']]

## 6. Sorting Data — `sort_values`

In [28]:
df.sort_values('Profit', ascending = False).head()

,Row_ID,Customer_ID,Customer_Name,Gender,Age,City,State,Country,Membership_Type,Order_ID,...,Time_On_Website,Rating,Returned_Product,Customer_Satisfaction,Salesperson,Region,Warehouse,Profit,Cost,Revenue
1520,1521,CUST01231,Ananya Nair,Female,50.0,Delhi,Delhi,India,Platinum,ORD102228,...,2.7,3.0,No,Very Unsatisfied,Agent_16,South,WH-South,₹974.38,3155.09,5197.42
2138,2139,CUST00058,Myra Gupta,Female,35.0,HYDERABAD,Telangana,India,Gold,ORD104080,...,14.0,NaN,No,Very Unsatisfied,Agent_04,South,WH-Central,₹945.28,3966.17,6084.91
4171,4172,CUST01462,Rohan Joshi,Male,NaN,Lucknow,Uttar Pradesh,India,Silver,ORD102624,...,3.1,4.0,No,NaN,Agent_12,North,WH-East,₹91.27,961.86,1329.95
368,369,CUST00405,Sai Iyer,Male,42.0,Chennai,Tamil Nadu,India,Regular,ORD100615,...,1.4,3.0,No,Unsatisfied,Agent_11,East,WH-East,₹886.73,1187.21,2601.70
2212,2213,CUST00877,Vivaan Mehta,Female,39.0,Hyderabad,Telangana,India,Gold,ORD100806,...,11.6,2.0,No,Unsatisfied,Agent_11,South,WH-Central,₹885.86,5237.01,7625.54

## 7. Exploring Categories — `value_counts`, `unique`, `nunique`

## 8. Handling Missing Values — `isnull`, `fillna`, `dropna`

In [31]:
df.isnull().sum()

Row_ID                     0
Customer_ID                0
Customer_Name              0
Gender                     0
Age                      430
City                     215
State                      0
Country                    0
Membership_Type            0
Order_ID                   0
Order_Date                 0
Delivery_Date            215
Payment_Method             0
Order_Status               0
Product_Category           0
Product_Name               0
Quantity                   0
Unit_Price                 0
Discount                 215
Shipping_Cost              0
Tax                        0
Total_Amount               0
Website_Visits             0
Time_On_Website            0
Rating                   430
Returned_Product           0
Customer_Satisfaction    430
Salesperson                0
Region                     0
Warehouse                  0
Profit                   861
Cost                       0
Revenue                    0
dtype: int64

In [32]:
df['Age'].skew()

2.599809823076897

In [33]:
age_median = df['Age'].median()
df['Age'] = df['Age'].fillna(age_median)

In [34]:
df['Age'].isnull().sum()

0

## 9. Duplicate Handling

In [36]:
df.duplicated().sum()

0

## 10. `groupby`, `agg`, and `transform`

In [38]:
df['Profit'] = (
    df['Profit']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [39]:
df['City'].unique()

array(['Chennai', 'Jaipur', 'Bhopal', 'Hyderabad', 'Ahmedabad', 'Indore',
       'Lucknow', 'Delhi', 'Bengaluru', 'Pune', 'jaipur', 'Mumbai',
       ' Ahmedabad ', 'AHMEDABAD', 'Kolkata', 'BENGALURU', 'kolkata', nan,
       'JAIPUR', 'LUCKNOW', 'MUMBAI', 'pune', ' Mumbai', 'PUNE',
       ' Kolkata ', 'Bangalore', ' Bhopal ', 'DELHI ', 'chennai',
       'bengaluru', ' Pune ', 'indore', ' Hyderabad ', 'KOLKATA',
       'lucknow', ' Jaipur ', 'CHENNAI', 'hyderabad', 'ahmedabad',
       'mumbai', ' Chennai ', 'New Delhi', ' Lucknow ', 'INDORE',
       ' Indore ', 'delhi', 'HYDERABAD', ' Bengaluru '], dtype=object)

In [40]:
# 1) Normalize to lowercase + strip spaces
city_norm = df['City'].str.strip().str.lower()

# 2) Define mapping on normalized values
city_map = {
    'bhopal': 'Bhopal',
    'jaipur': 'Jaipur',
    'hyderabad': 'Hyderabad',
    'ahmedabad': 'Ahmedabad',
    'indore': 'Indore',
    'lucknow': 'Lucknow',
    'delhi': 'Delhi',
    'new delhi': 'New Delhi',
    'bengaluru': 'Bengaluru',
    'bangalore': 'Bengaluru',
    'pune': 'Pune',
    'mumbai': 'Mumbai',
    'kolkata': 'Kolkata',
    'chennai': 'Chennai',
}

# 3) Apply mapping; keep original where no mapping
df['City'] = city_norm.map(city_map).fillna(df['City'])

In [41]:
df.groupby('City')['Profit'].sum().sort_values()

City
New Delhi      3163.28
Delhi        117635.28
Mumbai       179483.52
Kolkata      181629.33
Chennai      183061.23
Hyderabad    207707.58
Jaipur       249819.42
Lucknow      256587.91
Bengaluru    265955.87
Indore       274651.91
Pune         284973.61
Bhopal       300195.73
Ahmedabad    304275.88
Name: Profit, dtype: float64

## 11. Data Type Fixing (`astype`)

In [43]:
df.head(3)

,Row_ID,Customer_ID,Customer_Name,Gender,Age,City,State,Country,Membership_Type,Order_ID,...,Time_On_Website,Rating,Returned_Product,Customer_Satisfaction,Salesperson,Region,Warehouse,Profit,Cost,Revenue
0,1,CUST00265,Sneha Sharma,Male,35.0,Chennai,Tamil Nadu,India,Gold,ORD103884,...,5.8,4.0,No,Very Satisfied,Agent_15,South,WH-East,543.26,7950.40,10473.10
1,2,CUST01312,Rahul Joshi,Female,23.0,Jaipur,Rajasthan,India,Gold,ORD103992,...,6.7,2.0,No,Very Satisfied,Agent_17,South,WH-Central,316.68,2412.48,3388.61
2,3,CUST00608,Priya Mehta,Male,18.0,Bhopal,Madhya Pradesh,India,Regular,ORD103326,...,15.6,5.0,No,Satisfied,Agent_04,South,WH-East,1536.93,3649.22,6373.82

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4305 entries, 0 to 4304
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Row_ID                 4305 non-null   int64
 1   Customer_ID            4305 non-null   object
 2   Customer_Name          4305 non-null   object
 3   Gender                 4305 non-null   object
 4   Age                    4305 non-null   float64
 5   City                   4090 non-null   object
 6   State                  4305 non-null   object
 7   Country                4305 non-null   object
 8   Membership_Type        4305 non-null   object
 9   Order_ID               4305 non-null   object
 10  Order_Date             4305 non-null   object
 11  Delivery_Date          4090 non-null   object
 12  Payment_Method         4305 non-null   object
 13  Order_Status           4305 non-null   object
 14  Product_Category       4305 non-null   object
 15  Product_Name           4305 non-null   object
 16  Quantity               4305 non-null   int64
 17  Unit_Price             4305 non-null   object
 18  Discount               4090 non-null   float64
 19  Shipping_Cost          4305 non-null   float64
 20  Tax                    4305 non-null   float64
 21  Total_Amount           4305 non-null   float64
 22  Website_Visits         4305 non-null   int64
 23  Time_On_Website        4305 non-null   float64
 24  Rating                 3875 non-null   float64
 25  Returned_Product       4305 non-null   object
 26  Customer_Satisfaction  3875 non-null   object
 27  Salesperson            4305 non-null   object
 28  Region                 4305 non-null   object
 29  Warehouse              4305 non-null   object
 30  Profit                 3444 non-null   float64
 31  Cost                   4305 non-null   float64
 32  Revenue                4305 non-null   float64
dtypes: float64(10), int64(3), object(20)
memory usage: 1.1+ MB

In [45]:
df.iloc[:3, 8:20]

,Membership_Type,Order_ID,Order_Date,Delivery_Date,Payment_Method,Order_Status,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Shipping_Cost
0,Gold,ORD103884,16-Dec-2024,20-Dec-2024,Cash on Delivery,Cancelled,Fashion,Running Shoes,5,2253.08,7.033064,94.28
1,Gold,ORD103992,07/27/2023,30-Jul-2023,Debit Card,Delivered,Sports,Football,5,726.12,6.665189,49.50
2,Regular,ORD103326,16/12/2023,2023-12-25,Net Banking,Delivered,Home & Kitchen,Mixer Grinder,7,1345.5,32.326587,40.38

In [46]:
df['Unit_Price'].isnull().sum()

0

In [47]:
df['Unit_Price'] = df['Unit_Price'].str.replace(",","")

In [48]:
df['Unit_Price'] = pd.to_numeric(df['Unit_Price'], errors = 'coerce')

In [49]:
df['Unit_Price'].dtype

dtype('float64')

In [50]:
df['Order_Date'].dtype

dtype('O')

In [96]:
df['Order_Date'].isna().sum()

0

In [98]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format = 'mixed', errors = 'coerce')

In [100]:
df['Order_Date'].head(5)

0   2024-12-16
1   2023-07-27
2   2023-12-16
3   2023-07-08
4   2024-10-26
Name: Order_Date, dtype: datetime64[ns]

In [102]:
df['Order_Date'].isna().sum()

0