# Data Cleaning Assignment (Pandas)

Dataset: **movies_dataset.csv**

Complete all questions using Pandas.

## Q1. Import pandas and load the dataset.

In [3]:
import pandas as pd

df = pd.read_csv("movies_dataset.csv")

## Q2. Display first 10 rows.

In [5]:
df.head(10)

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
0,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
1,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
2,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
3,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
4,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released
5,6,RRR,Scifi,2021,9.8,97 min,Director 17,NaN,English,$76M,"263,811",Disney+ Hotstar,PG-13,20-02-2023,Upcoming
6,7,Moana,Action,2023,8.3,148 min,Director 25,Japan,NaN,$170M,"564,003",Disney+ Hotstar,A,17-03-2024,Released
7,8,Pushpa,Sci-Fi,2019,5.8,179 min,Director 17,India,Spanish,$29M,"471,899",Amazon Prime,U/A,02-04-2024,Released
8,9,Titanic,Acton,2024,8.2,150 min,Director 6,Japan,Spanish,$236M,"652,773",Disney+ Hotstar,U/A,23-05-2023,Upcoming
9,10,Moana,Sci-Fi,2019,NaN,82 min,Director 19,Canada,Spanish,$56M,"160,234",Netflix,U,28-06-2020,Released

## Q3. Display last 10 rows.

In [7]:
df.tail(10)

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
295,296,Avatar,Comedy,2021,NaN,134 min,Director 13,UK,NaN,$248M,"419,340",Netflix,U,25-08-2024,Released
296,297,Titanic,Animation,2018,8.3,170 min,Director 25,NaN,HINDI,$134M,"731,264",Amazon Prime,PG-13,06-12-2025,Upcoming
297,298,KGF,Animation,2018,7.2,101 min,Director 10,india,Spanish,$280M,"937,731",Netflix,A,18-11-2020,Upcoming
298,299,Moana,Scifi,2019,9.7,129 min,Director 3,india,Hindi,$240M,"545,580",Amazon Prime,U/A,06-11-2025,Released
299,300,Joker,Horror,2022,7.1,119 min,Director 13,USA,Spanish,$214M,"760,676",Netflix,U,07-03-2024,Released
300,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
301,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
302,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
303,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
304,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released

## Q4. Print shape.

In [9]:
df.shape

(305, 15)

## Q5. Print column names.

In [11]:
df.columns.tolist()

['Movie_ID',
 'Title',
 'Genre',
 'Release_Year',
 'Rating',
 'Duration',
 'Director',
 'Country',
 'Language',
 'Budget',
 'Revenue',
 'Platform',
 'Age_Rating',
 'Added_Date',
 'Status']

## Q6. Use info().

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie_ID      305 non-null    int64
 1   Title         282 non-null    object
 2   Genre         305 non-null    object
 3   Release_Year  305 non-null    int64
 4   Rating        278 non-null    float64
 5   Duration      305 non-null    object
 6   Director      305 non-null    object
 7   Country       272 non-null    object
 8   Language      240 non-null    object
 9   Budget        270 non-null    object
 10  Revenue       282 non-null    object
 11  Platform      305 non-null    object
 12  Age_Rating    305 non-null    object
 13  Added_Date    305 non-null    object
 14  Status        305 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 35.9+ KB

## Q7. Use describe().

In [15]:
df.describe()

         Movie_ID  Release_Year      Rating
count  305.000000    305.000000  278.000000
mean   148.081967   2021.108197    7.466547
std     88.052447      2.002818    1.321495
min      1.000000   2018.000000    5.000000
25%     72.000000   2019.000000    6.500000
50%    148.000000   2021.000000    7.500000
75%    224.000000   2023.000000    8.500000
max    300.000000   2024.000000    9.800000

In [16]:
df.describe(include='all')

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
count,305.000000,282,305,305.000000,278.000000,305,305,272,240,270,282,305,305,305,305
unique,NaN,30,11,NaN,NaN,95,25,7,5,163,277,3,4,282,2
top,NaN,Moana,Action,NaN,NaN,122 min,Director 12,Japan,Spanish,$39M,"338,517",Disney+ Hotstar,A,18-04-2025,Released
freq,NaN,23,36,NaN,NaN,7,18,44,58,5,2,110,88,3,160
mean,148.081967,NaN,NaN,2021.108197,7.466547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,88.052447,NaN,NaN,2.002818,1.321495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,2018.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,72.000000,NaN,NaN,2019.000000,6.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,148.000000,NaN,NaN,2021.000000,7.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,224.000000,NaN,NaN,2023.000000,8.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,300.000000,NaN,NaN,2024.000000,9.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Q8. Find missing values.

In [18]:
df.isnull().sum()

Movie_ID         0
Title           23
Genre            0
Release_Year     0
Rating          27
Duration         0
Director         0
Country         33
Language        65
Budget          35
Revenue         23
Platform         0
Age_Rating       0
Added_Date       0
Status           0
dtype: int64

## Q9. Check duplicate rows.

In [20]:
df[df.duplicated()]

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
300,1,NaN,Romance,2019,8.5,166 min,Director 24,USA,Spanish,$35M,"338,517",Disney+ Hotstar,U,18-04-2025,Upcoming
301,2,The Batman,Action,2024,8.4,123 min,Director 9,UK,Hindi,$192M,"489,099",Amazon Prime,A,20-05-2020,Upcoming
302,3,Jawan,Acton,2020,8.0,126 min,Director 19,Canada,NaN,NaN,"891,296",Netflix,U/A,28-02-2023,Upcoming
303,4,Moana,Horror,2020,6.3,167 min,Director 21,USA,Spanish,$293M,"267,473",Amazon Prime,A,21-12-2024,Released
304,5,KGF,Sci-Fi,2024,NaN,120 min,Director 13,Japan,English,$181M,"611,405",Disney+ Hotstar,PG-13,05-05-2021,Released

## Q10. Remove duplicate rows.

In [22]:
df.drop_duplicates(inplace = True)

In [23]:
df.shape

(300, 15)

## Q11. Remove extra spaces from Title.

In [25]:
df['Title'] = df['Title'].str.strip()

## Q12. Convert Title to Proper Case.

In [27]:
df['Title'] = df['Title'].str.title()

In [28]:
df['Title']

0             NaN
1      The Batman
2           Jawan
3           Moana
4             Kgf
          ...
295        Avatar
296       Titanic
297           Kgf
298         Moana
299         Joker
Name: Title, Length: 300, dtype: object

## Q13. Correct Genre spellings (Acton→Action, Scifi→Sci-Fi, Romnce→Romance).

In [30]:
df['Genre'].unique()

array(['Romance', 'Action', 'Acton', 'Horror', 'Sci-Fi', 'Scifi', 'Drama',
       'Comedy', 'Thriller', 'Romnce', 'Animation'], dtype=object)

In [31]:
genre_mapping = {
    "Acton": "Action",
    "Scifi": "Sci-Fi",
    "Romnce": "Romance"
}

In [32]:
df['Genre'] = df['Genre'].replace(genre_mapping)

In [33]:
df['Genre']

0        Romance
1         Action
2         Action
3         Horror
4         Sci-Fi
         ...
295       Comedy
296    Animation
297    Animation
298       Sci-Fi
299       Horror
Name: Genre, Length: 300, dtype: object

In [34]:
df['Genre'].unique()

array(['Romance', 'Action', 'Horror', 'Sci-Fi', 'Drama', 'Comedy',
       'Thriller', 'Animation'], dtype=object)

## Q14. Convert Country to upper case.

In [36]:
df['Country']

0         USA
1          UK
2      Canada
3         USA
4       Japan
        ...
295        UK
296       NaN
297     india
298     india
299       USA
Name: Country, Length: 300, dtype: object

In [37]:
df['Country'].unique()

array(['USA', 'UK', 'Canada', 'Japan', nan, 'India', 'india', ' usa '],
      dtype=object)

In [38]:
df['Country'] = df['Country'].str.upper()

In [39]:
df['Country']

0         USA
1          UK
2      CANADA
3         USA
4       JAPAN
        ...
295        UK
296       NaN
297     INDIA
298     INDIA
299       USA
Name: Country, Length: 300, dtype: object

In [40]:
df['Country'].unique()

array(['USA', 'UK', 'CANADA', 'JAPAN', nan, 'INDIA', ' USA '],
      dtype=object)

In [41]:
df['Country'] = df['Country'].str.strip()

In [42]:
df['Country'].unique()

array(['USA', 'UK', 'CANADA', 'JAPAN', nan, 'INDIA'], dtype=object)

## Q15. Convert Language to lower case.

In [44]:
df['Language'] = df['Language'].str.lower()

In [45]:
df['Language']

0      spanish
1        hindi
2          NaN
3      spanish
4      english
        ...
295        NaN
296      hindi
297    spanish
298      hindi
299    spanish
Name: Language, Length: 300, dtype: object

In [46]:
df['Language'].unique()

array(['spanish', 'hindi', nan, 'english'], dtype=object)

## Q16. Convert Rating to float.

In [48]:
# Rating is already in float

df['Rating'].dtype

dtype('float64')

## Q17. Remove 'min' from Duration and convert to integer.

In [50]:
df['Duration']

0      166 min
1      123 min
2      126 min
3      167 min
4      120 min
        ...
295    134 min
296    170 min
297    101 min
298    129 min
299    119 min
Name: Duration, Length: 300, dtype: object

In [51]:
df['Duration'].dtype

dtype('O')

In [52]:
df['Duration'] = df['Duration'].str.replace("min","")
df['Duration']

0      166
1      123
2      126
3      167
4      120
       ...
295    134
296    170
297    101
298    129
299    119
Name: Duration, Length: 300, dtype: object

In [53]:
df['Duration'] = df['Duration'].astype(int)

In [54]:
df['Duration'].dtype

dtype('int64')

## Q18. Remove '$' and 'M' from Budget.

In [56]:
df['Budget']

0       $35M
1      $192M
2        NaN
3      $293M
4      $181M
       ...
295    $248M
296    $134M
297    $280M
298    $240M
299    $214M
Name: Budget, Length: 300, dtype: object

In [57]:
df['Budget'] = df['Budget'].str.replace("$", "").str.replace("M", "")
df['Budget']

0       35
1      192
2      NaN
3      293
4      181
      ...
295    248
296    134
297    280
298    240
299    214
Name: Budget, Length: 300, dtype: object

## Q19. Remove commas from Revenue and convert numeric.

In [59]:
df['Revenue']

0      338,517
1      489,099
2      891,296
3      267,473
4      611,405
        ...
295    419,340
296    731,264
297    937,731
298    545,580
299    760,676
Name: Revenue, Length: 300, dtype: object

In [60]:
df['Revenue'] = df['Revenue'].str.replace(",", "")

In [61]:
df['Revenue']

0      338517
1      489099
2      891296
3      267473
4      611405
        ...
295    419340
296    731264
297    937731
298    545580
299    760676
Name: Revenue, Length: 300, dtype: object

In [62]:
df.isna().sum()

Movie_ID         0
Title           22
Genre            0
Release_Year     0
Rating          26
Duration         0
Director         0
Country         33
Language        64
Budget          34
Revenue         23
Platform         0
Age_Rating       0
Added_Date       0
Status           0
dtype: int64

In [63]:
df['Revenue'] = pd.to_numeric(df['Revenue'])

In [64]:
df['Revenue'].dtype

dtype('float64')

## Q20. Convert Release_Year to integer.

In [66]:
df['Release_Year'].dtype

dtype('int64')

## Q21. Convert Added_Date to datetime.

In [68]:
df['Added_Date'].dtype

dtype('O')

pd.to_datetime` is built to read your string dates like ‎`18-04-2025`, and ‎`dayfirst=True` means when ‎`DD-MM-YYYY` format.

In [70]:
df['Added_Date'] = pd.to_datetime(df['Added_Date'])

/var/folders/tj/5m337bwx0gndn28_h0bqpcz00000gn/T/ipykernel_4383/3447673004.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Added_Date'] = pd.to_datetime(df['Added_Date'])

In [71]:
df['Added_Date']

0     2025-04-18
1     2020-05-20
2     2023-02-28
3     2024-12-21
4     2021-05-05
         ...
295   2024-08-25
296   2025-12-06
297   2020-11-18
298   2025-11-06
299   2024-03-07
Name: Added_Date, Length: 300, dtype: datetime64[ns]

## Q22. Delete rows where Title is missing.

In [73]:
df.shape

(300, 15)

In [74]:
df = df.dropna(subset=['Title'])

In [75]:
df.shape

(278, 15)

In [76]:
df

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
1,2,The Batman,Action,2024,8.4,123,Director 9,UK,hindi,192,489099.0,Amazon Prime,A,2020-05-20,Upcoming
2,3,Jawan,Action,2020,8.0,126,Director 19,CANADA,NaN,NaN,891296.0,Netflix,U/A,2023-02-28,Upcoming
3,4,Moana,Horror,2020,6.3,167,Director 21,USA,spanish,293,267473.0,Amazon Prime,A,2024-12-21,Released
4,5,Kgf,Sci-Fi,2024,NaN,120,Director 13,JAPAN,english,181,611405.0,Disney+ Hotstar,PG-13,2021-05-05,Released
5,6,Rrr,Sci-Fi,2021,9.8,97,Director 17,NaN,english,76,263811.0,Disney+ Hotstar,PG-13,2023-02-20,Upcoming
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,Avatar,Comedy,2021,NaN,134,Director 13,UK,NaN,248,419340.0,Netflix,U,2024-08-25,Released
296,297,Titanic,Animation,2018,8.3,170,Director 25,NaN,hindi,134,731264.0,Amazon Prime,PG-13,2025-12-06,Upcoming
297,298,Kgf,Animation,2018,7.2,101,Director 10,INDIA,spanish,280,937731.0,Netflix,A,2020-11-18,Upcoming
298,299,Moana,Sci-Fi,2019,9.7,129,Director 3,INDIA,hindi,240,545580.0,Amazon Prime,U/A,2025-11-06,Released
299,300,Joker,Horror,2022,7.1,119,Director 13,USA,spanish,214,760676.0,Netflix,U,2024-03-07,Released

## Q23. Fill missing Rating with mean.

In [143]:
fill_mean = df['Rating'].mean()
df['Rating'] = df['Rating'].fillna(fill_mean)

In [145]:
df['Rating'].isnull().sum()

0

In [147]:
df['Rating']

1      8.400000
2      8.000000
3      6.300000
4      7.440392
5      9.800000
         ...
295    7.440392
296    8.300000
297    7.200000
298    9.700000
299    7.100000
Name: Rating, Length: 278, dtype: float64

## Q24. Fill missing Country with mode.

In [161]:
df['Country'].mode()

0    INDIA
Name: Country, dtype: object

In [155]:
fill_mode = df['Country'].mode()[0]
df['Country'] = df['Country'].fillna(fill_mode)

In [157]:
df['Country'].isnull().sum()

0

In [159]:
df['Country']

1          UK
2      CANADA
3         USA
4       JAPAN
5       INDIA
        ...
295        UK
296     INDIA
297     INDIA
298     INDIA
299       USA
Name: Country, Length: 278, dtype: object

## Q25. Fill missing Budget with median.

In [165]:
df['Budget'] = pd.to_numeric(df['Budget'], errors='coerce')

In [167]:
fill_budget = df['Budget'].median()
df['Budget'] = df['Budget'].fillna(fill_budget)

In [169]:
df['Budget']

1      192.0
2      171.0
3      293.0
4      181.0
5       76.0
       ...
295    248.0
296    134.0
297    280.0
298    240.0
299    214.0
Name: Budget, Length: 278, dtype: float64

## Q26. Check if any null values remain.

In [173]:
df.isnull().sum()

Movie_ID         0
Title            0
Genre            0
Release_Year     0
Rating           0
Duration         0
Director         0
Country          0
Language        59
Budget           0
Revenue         22
Platform         0
Age_Rating       0
Added_Date       0
Status           0
dtype: int64

## Q27. Save cleaned dataset as clean_movies_dataset.csv.

In [175]:
df.to_csv('clean_movies_dataset.csv', index=False)

## Q28. Print Top 5 highest rated movies.

In [181]:
df.sort_values('Rating', ascending=False).head(5)

,Movie_ID,Title,Genre,Release_Year,Rating,Duration,Director,Country,Language,Budget,Revenue,Platform,Age_Rating,Added_Date,Status
5,6,Rrr,Sci-Fi,2021,9.8,97,Director 17,INDIA,english,76.0,263811.0,Disney+ Hotstar,PG-13,2023-02-20,Upcoming
298,299,Moana,Sci-Fi,2019,9.7,129,Director 3,INDIA,hindi,240.0,545580.0,Amazon Prime,U/A,2025-11-06,Released
81,82,Titanic,Action,2022,9.7,150,Director 1,USA,hindi,171.0,482259.0,Disney+ Hotstar,U,2022-02-12,Released
53,54,Kgf,Drama,2024,9.7,147,Director 17,JAPAN,hindi,266.0,402764.0,Amazon Prime,U,2021-02-15,Released
105,106,Pushpa,Sci-Fi,2022,9.7,116,Director 15,INDIA,hindi,259.0,928115.0,Amazon Prime,U/A,2025-08-24,Upcoming

## Q29. Count movies platform-wise.

In [185]:
df.groupby('Platform')['Movie_ID'].count()

Platform
Amazon Prime        82
Disney+ Hotstar    100
Netflix             96
Name: Movie_ID, dtype: int64

In [187]:
df.groupby('Platform')['Movie_ID'].count().reset_index(name='Movie_Count') \
  .sort_values('Movie_Count', ascending=False)

          Platform  Movie_Count
1  Disney+ Hotstar          100
2          Netflix           96
0     Amazon Prime           82